version: '3'
services:
  grafana:
    image: "grafana/grafana"
    ports:
     - "4200:4200"

  influxdb:
    image: "influxdb"
    ports:
     - "8086:8086"
    environment:
      - INFLUXDB_DB=influxDB